name: Sync from upstream

on:
  schedule:
  - cron: '0 7 */7 * *' # At 07:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-datadog-app-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Sync datadog from upstream
        uses: giantswarm/subtree-util@v0.2.0
        with:
          target_github_token: ${{ secrets.ARCHITECT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/datadog-app
          target_path: helm/datadog
          source_tag_wildcard: "datadog-[0-9]*"
          source_path: charts/datadog
